version: '2'
services:
  angular:
    hostname: localhost
    container_name: ng-web
    build: .
    ports:
      - "8080:8080"
    networks:
      vpcbr:
	ipv4_address: 10.128.0.2
    volumes:
    - .:/SPA
